version: "3.8"

volumes:
  widget-mongodb:

services:
  mongodb:
    image: "mongo:latest"
    environment:
      "MONGO_INITDB_ROOT_USERNAME": "widget"
      "MONGO_INITDB_ROOT_PASSWORD": "secret"
    ports:
      - "27017:27017"
    volumes:
      - "widget-mongodb:/data/db"

  server:
    build:
      context: "./server"
      target: "develop-stage"
    depends_on:
      - "mongodb"
    env_file:
      - "./server/.env"
    ports:
      - "8081:8081"
    volumes:
      - "./server/src:/app/src"
      - "./server/tests:/app/tests"
    command: '/bin/sh -c "yarn serve"'

  client:
    build:
      context: "./client"
      target: "develop-stage"
    ports:
      - "8080:8080"
    volumes:
      - "./client/src:/app/src"
      - "./client/public:/app/public"
      - "./client/tests:/app/tests"
    command: '/bin/sh -c "yarn serve"'
